"""Markdown report generation for GitPulse."""

from __future__ import annotations

from .analyzer import GitRepository


def _fmt(value: float) -> str:
    return f"{value:g}"


def render_markdown(repo: GitRepository) -> str:
    """Render a full Markdown report for ``repo``."""
    summary = repo.summary()
    contributors = repo.contributors()
    weekly = repo.weekly_activity(max_weeks=26)
    churn = repo.churn(top=10)

    lines: list[str] = [f"# GitPulse report", ""]

    lines.append(f"Repository: **{summary.path}**  ")
    lines.append(f"Branch: `{summary.branch}`")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Commits | {summary.total_commits} |")
    lines.append(f"| Authors | {summary.total_authors} |")
    lines.append(f"| Lines added | {summary.total_added} |")
    lines.append(f"| Lines removed | {summary.total_removed} |")
    lines.append(f"| Files touched | {summary.files_touched} |")
    lines.append(f"| Bus factor | {summary.bus_factor} |")
    lines.append(
        f"| Avg commits / week | {_fmt(summary.avg_commits_per_week)} |"
    )
    lines.append("")

    lines.append("## Contributors")
    lines.append("")
    lines.append("| Author | Commits | Share |")
    lines.append("| --- | ---: | ---: |")
    for contributor in contributors:
        lines.append(
            f"| {contributor.name} | {contributor.commits} | "
            f"{contributor.share(summary.total_commits) * 100:.1f}% |"
        )
    lines.append("")

    lines.append("## Weekly activity")
    lines.append("")
    for week in weekly:
        lines.append(f"- `{week.week_start}` — {week.commits} commit(s)")
    lines.append("")

    lines.append("## Top churned paths")
    lines.append("")
    lines.append("| Path | Added | Removed |")
    lines.append("| --- | ---: | ---: |")
    for file_stats in churn:
        lines.append(
            f"| `{file_stats.path}` | {file_stats.added} | {file_stats.removed} |"
        )
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by GitPulse — {summary.path}*")
    return "\n".join(lines)


__all__ = ["render_markdown"]